# Generated by Django 2.2.9 on 2022-12-08 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20221208_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='Adress',
            new_name='adress',
        ),
    ]
