# Generated by Django 2.2.9 on 2022-12-08 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20221208_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='adress',
            new_name='slug',
        ),
    ]
